INSERT INTO <db>.<table> (movieTitle, description, releaseDate, price, url, category, imageUrl) VALUES 
("Twilight", "Bella Swan doesn't expect much when she moves to the small town of Forks, Washington, until she meets the mysterious and handsome Edward Cullen - a boy who's hiding a dark secret: he's a vampire. As their worlds and hearts collide, Edward must battle the bloodlust raging inside him as well as a coterie of undead that would make Bella their prey. Based on the #1 New York Times best-selling sensation by Stephanie Meyer, Twilight adds a dangerous twist to the classic story of star-crossed lovers.", "01/01/08", 5, "https://www.youtube.com/embed/zZUUHthMeA4", "DRAMA", "https://i.ytimg.com/vi_webp/zZUUHthMeA4/movieposter_en.webp"),
("Downton Abbey", "The worldwide phenomenon, Downton Abbey, returns in a spectacular motion picture, as the beloved Crawleys and their intrepid staff prepare for the most important moment of their lives. A royal visit from the King and Queen of England unleashes scandal, romance and intrigue that leave the future of Downton hanging in the balance. Written by series creator Julian Fellowes and starring the original cast, this grand cinematic experience will have you cheering for your favorite characters all over again.", "01/01/19", 3, "https://www.youtube.com/embed/C6B_vpWFb0w", "DRAMA", "https://i.ytimg.com/vi_webp/C6B_vpWFb0w/movieposter.webp"),
("Life Of Pi", "Embark on the adventure of a lifetime in this visual masterpiece from Oscar winner Ang Lee*, based on the best-selling novel. After a cataclysmic shipwreck, an Indian boy named Pi finds himself stranded on a lifeboat with a ferocious Bengal tiger. Together, they face nature's majestic grandeur and fury on an epic journey of discovery.", "01/01/12", 14, "https://youtu.be/ZUee5f-DycQ", "DRAMA", "https://i.ytimg.com/vi_webp/ZUee5f-DycQ/movieposter.webp"),
("Noah", "When God decides that mankind has become too sinful and must be wiped off the Earth, he chooses Noah, a pious man, for a great task. Noah must build an ark large enough to hold his wife, adopted daughter, sons and their wives -- plus breeding pairs of every animal. When the task is completed, Noah and his family witness God's wrath in the form of an apocalyptic flood.", "01/01/14", 2, "https://youtu.be/o7NMrTaawbo", "DRAMA", "https://i.ytimg.com/vi_webp/o7NMrTaawbo/movieposter.webp"),

("Jurassic World", "The Jurassic World theme park lets guests experience the thrill of witnessing actual dinosaurs, but something ferocious lurks behind the park's attractions - a genetically modified dinosaur with savage capabilities. When the massive creature escapes, chaos erupts across the island. Now it's up to Owen and Claire to save the park's tourists from an all-out prehistoric assault.", "01/01/15", 4, "https://youtu.be/k43lG8yoCzg", "ACTION", "https://i.ytimg.com/vi_webp/k43lG8yoCzg/movieposter.webp"),
("Max Steel", "Teenager Max McGrath is adjusting to a new school when his body starts to generate strange energy flare-ups that he can't control. Max is then rescued by Steel, an extraterrestrial who has been secretly monitoring his progress.", "01/01/16", 8, "https://youtu.be/N9yKvmbQNZ8", "ACTION", "https://i.ytimg.com/vi_webp/N9yKvmbQNZ8/movieposter_en.webp"),
("The Mummy", "Deep in the Egyptian desert, a handful of people searching for a long-lost treasure have just unearthed a 3,000 year old legacy of terror.", "01/01/99", 17, "https://youtu.be/5d_wkxeTplo", "ACTION", "https://i.ytimg.com/vi_webp/5d_wkxeTplo/movieposter_en.webp"),
("The Great Wall", "An elite force making a valiant stand for humanity on the world's most iconic structure.", "01/01/17", 5, "https://www.youtube.com/embed/fAVfJAbYaJ8", "ACTION", "https://i.ytimg.com/vi_webp/fAVfJAbYaJ8/movieposter_en.webp"),

("Barnyard", "Move over, all you pretenders...here are the original party animals -- the animated gang of Barnyard!  This laugh-filled adventure stars Otis, a carefree cow who spends his days singing, dancing and playing tricks on humans...much to the dismay of his father.", "01/01/06", 2, "https://youtu.be/LFHtHcIT_Rk", "COMEDY", "https://i.ytimg.com/vi_webp/LFHtHcIT_Rk/movieposter.webp"),
("Jimmy Neutron: Boy Genius", "JIMMY NEUTRON: Boy Genius, is trying to make contact with an alien civilization. Unbeknownst to him, a satellite he launches (okay, it's the kitchen toaster, but it works!) is picked up by an alien species. In the dark of night the aliens fly their war ships-looking like a fleet of rubber chickens to earth and abduct all the parents in Jimmy's hometown of Retroville. So it's up to Jimmy to create a fleet of space ships from the rides at the town's new amusement park (hey, he's a genius, remember?) and launch them into orbit in a bid to rescue the abducted parents of Retroville. But Jimmy better hurry! Because the aliens are preparing to use the parents as human sacrifices! With his robotic dog, Goddard, and his best friend, Carl, by his side, Jimmy and the rest of the kids in Retroville take to the skies on a trip that's sure to be a blast! Featuring the voice talents of Patrick Stewart and Martin Short as the evil King Goobot and his sidekick Ooblar.", "01/01/01", 8, "https://youtu.be/dQB4HJfVj2Q", "COMEDY", "https://i.ytimg.com/vi_webp/dQB4HJfVj2Q/movieposter_en.webp"),
("Ella Enchanted", "On the day she's born, Ella is given the gift of obedience by her Fairy Godmother. Unable to refuse to do anything she's asked—no matter how wicked—Ella sets off to return the gift. But her simple journey soon turns into an amazing magical adventure bursting with colorful characters, music, wit, and whimsy.", "01/01/04", 12, "https://youtu.be/EjOkAjfOGns", "COMEDY", "https://i.ytimg.com/vi_webp/EjOkAjfOGns/movieposter_en.webp"),
("Scooby-doo: The Movie", "
Zoinks! Two years after a clash of egos forced Mystery Inc. to close it's doors, Scooby-Doo and his clever crime-solving cohorts Fred, Daphne, Shaggy and Velma are individually summoned to Spooky Island to investigate a series of paranormal incidents at the ultra-hip Spring Break hot spot. Concerned that his frightfully popular resort might truly be haunted, Spooky Island owner Emile Mondavarious tries to reunite those notoriously meddling detectives to solve the mystery before his supernatural secret scares away the college crowds. Scooby and the gang will have to overcome their personal differences and forget everything they think they know about fake ghouls and phony creatures to crack the case, save themselves and possibly...the world! Ruh-roh!", "01/01/02", 11, "https://youtu.be/WFglNabL7Sg", "COMEDY", "https://i.ytimg.com/vi_webp/WFglNabL7Sg/movieposter.webp"),
("Tim Burton's Corpse Bride", "Returning to the painstaking stop-motion animation he employed with amazing success in The Nightmare Before Christmas, Tim Burton presents a hair-raising legend based on a 19th-century Russian folktale, in which a young man mistakenly weds a corpse while on a two-day trek to the village of his real bride-to-be. It is up to the groom's flesh-and-blood fiancée, who has been pining for the arrival of her intended, to face her wraith-like rival and make peace with her by promising to live her dreams for her and by vowing to remember her always. Only then are the living bride and groom free to proceed with their own wedding ceremony in the warmhearted fable Tim Burton's Corpse Bride.", "01/01/05", 7, "https://youtu.be/9l9Se-4QbdY", "COMEDY", "https://i.ytimg.com/vi_webp/9l9Se-4QbdY/movieposter_en.webp"),
("The Nutty Professor", " Dr. Sherman Klump, a kind, calorically-challenged genetics professor who longs to shed his 400-pound frame in order to win the heart of beautiful Jada Pinkett. So, with one swig of his experimental fat-reducing serum, Sherman becomes Buddy Love, a fast-talking, pumped-up, plumped-down Don Juan. Can Sherman stop his buff alter ego before it's too late, or will Buddy have the last laugh? ", "01/01/96", 9, "https://youtu.be/tt8SxmlTFQg", "COMEDY", "https://i.ytimg.com/vi_webp/tt8SxmlTFQg/movieposter_en.webp"),
("Nacho Libre", "Ignacio, a disrespected cook at a Mexican monastery that can barely afford to feed the orphans who live there.  Inspired by a local wrestling hero, he decides to moonlight as the not-so-famous Luchador Nacho Libre to earn money for the monastery -- not to mention the admiration of beautiful nun Sister Encarnacion.", "01/01/06", 10, "https://youtu.be/WXAryQxtVbE", "COMEDY", "https://i.ytimg.com/vi_webp/WXAryQxtVbE/movieposter.webp"),
("The Book of Life", "A young man who embarks on an adventure that spans three fantastical worlds where he must face his greatest fears. Rich with a fresh take on pop music favorites and featuring a unique visual style, it’s a story that encourages us to celebrate the past and look forward to the future.", "01/01/14", 10, "https://youtu.be/7ePa0VGQpTE", "COMEDY", "https://i.ytimg.com/vi_webp/7ePa0VGQpTE/movieposter.webp"),
("Heathers", "A dark comedy about a teenager named Veronica Sawyer who tries to navigate high school by joining the most popular clique, the Heathers.", "01/01/88", 10, "https://youtu.be/Kuwu30JAyO0", "COMEDY", "https://i.ytimg.com/vi_webp/Kuwu30JAyO0/movieposter_en.webp"),
("Robots", "Heading for the big city to pursue his dreams of helping robots everywhere with his talent for invention, a small town robot named Rodney Copperbottom embarks on the adventure of a lifetime.  With the help of his misfit mechanical friends--Cappy, a beautiful, dynamic and savvy bot with whom Rodney is instantly smitten; Bigweld, a master inventor who has lost his way; and a group of misfit bots known as the Rusties, led by Fender and Piper Pinwheeler.  Rodney and his pals take on the evil corporate tyrant Ratchet to prove that you can shine no matter what you're made of.", "01/01/05", 10, "https://youtu.be/ojLBv8pERPI", "COMEDY", "https://i.ytimg.com/vi_webp/ojLBv8pERPI/movieposter.webp");
